server:
    port: 2001

spring:
    application:
        name: wsw-cloud-order-service

    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848  # ≈‰÷√nacosµÿ÷∑

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db2020?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: wsw19980801

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.wsw.cloudtest.domain
