server:
    port: 2002

spring:
    application:
        name: wsw-cloud-storage-service

    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848  # 配置nacos地址
        sentinel:
            transport:
                dashboard: localhost:9090  # sentinel dashboard地址
                port: 8719  # sentinel api port
            # sentinel配置持久化
            datasource:
                ds1:
                    nacos:
                        server-addr: localhost:8848
                        dataId: wsw-cloud-storage-service
                        groupId: DEFAULT_GROUP
                        data-type: json
                        rule-type: flow

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db2020?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: wsw19980801

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.wsw.cloudtest.domain

management:
    endpoints:
        web:
            exposure:
                include: '*'